{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy-vpn.fullname" . }}-worker
  labels:
    {{- include "proxy-vpn.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "proxy-vpn.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "proxy-vpn.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- if .Values.region }}
        region: {{ .Values.region | quote }}
        {{- end }}
      annotations:
        checksum/env: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.topologySpread.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.topologySpread.maxSkew }}
          topologyKey: {{ .Values.topologySpread.topologyKey }}
          whenUnsatisfiable: {{ .Values.topologySpread.whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "proxy-vpn.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: worker
      {{- end }}
      containers:
        - name: worker
          image: {{ include "proxy-vpn.image" (dict "Values" .Values "Chart" .Chart "bin" "worker" "override" .Values.worker.imageOverride) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "proxy-vpn.envSecretName" . }}
          resources: {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
